import type { Metadata } from "next";
import Link from "next/link";
import { SeoPageShell, sectionClass } from "@/components/SeoPageShell";
import { absoluteUrl } from "@/lib/site";

export const metadata: Metadata = { title: "Privacy Policy", description: "How Get Codex Theme handles social sign-in, public theme submissions, downloads, likes, abuse prevention, and retention.", alternates: { canonical: absoluteUrl("/privacy") } };

export default function PrivacyPage() {
  return (
    <SeoPageShell eyebrow="Legal · Updated July 23, 2026" title="Privacy Policy" description={<p>Browsing and downloading are anonymous. An account is required only to publish and manage a community theme.</p>} breadcrumbs={[{ label: "Home", href: "/" }, { label: "Privacy" }]} compact>
      <article className={`${sectionClass} max-w-4xl space-y-12 text-base leading-8 text-white/62`}>
        <section><h2 className="[font-family:var(--font-heading)] text-4xl text-white">1. Information we process</h2><p className="mt-5">You can browse, search, like, and download themes without creating an account. When you sign in with Google or GitHub to publish, Neon Auth provides the account identifier, name, email address, provider, and session data needed to authenticate the publisher. Publishing requires exactly one public contributor profile. A GitHub profile may be linked through Neon Auth. For X attribution, you provide a public profile URL; we normalize and store its username and canonical profile URL. Get Codex Theme does not call the X API or receive an X access token, refresh token, posts, or email address.</p></section>
        <section><h2 className="[font-family:var(--font-heading)] text-4xl text-white">2. Public submissions</h2><p className="mt-5">A CLI-submitted theme archive, manifest, preview images, automatically inferred category, and the single selected GitHub or X attribution are stored for automated validation. When validation succeeds, the theme assets, contributor username, profile link, license, version, and install metadata become public. GitHub attribution comes from the connected account; X attribution comes from the public profile URL supplied by the publisher. Do not submit private or confidential material or a profile you are not authorized to represent.</p></section>
        <section><h2 className="[font-family:var(--font-heading)] text-4xl text-white">3. Likes, reports, and abuse prevention</h2><p className="mt-5">For signed-in likes, we derive a one-way HMAC identifier from the authenticated user ID. For anonymous likes and private content reports, we derive a purpose-specific one-way HMAC identifier from the Cloudflare-provided IP address. We store only the resulting hash, never the raw IP address or raw user ID. A private report may include the report type, affected theme, optional contact email and evidence URL, and the details you submit.</p></section>
        <section><h2 className="[font-family:var(--font-heading)] text-4xl text-white">4. Storage and retention</h2><p className="mt-5">Submission records may be retained to preserve theme ownership, security evidence, and reproducible releases. Private reports are retained while a correction, rights, privacy, abuse, or removal request is investigated and for a reasonable period needed for legal compliance and repeat-abuse prevention. A creator may request removal of a public theme, while limited records may be retained for those purposes.</p></section>
        <section><h2 className="[font-family:var(--font-heading)] text-4xl text-white">5. Service providers</h2><p className="mt-5">We use Cloudflare for hosting, object storage, database services, and network security; Neon Auth for Google or GitHub sign-in and GitHub profile linking; and GitHub for the open-source repository and CLI release. X is not a website sign-in method and its API is not used for contributor attribution. We do not sell personal information and do not use payment processors because the service does not sell theme packs.</p></section>
        <section><h2 className="[font-family:var(--font-heading)] text-4xl text-white">6. Your choices</h2><p className="mt-5">You may browse without signing in, remove your own like by pressing the like button again, sign out at any time, and request correction or deletion of account-associated submission information subject to the integrity and legal exceptions above.</p></section>
        <section><h2 className="[font-family:var(--font-heading)] text-4xl text-white">7. Contact and changes</h2><p className="mt-5">Material changes will be reflected by the updated date on this page. For privacy, removal, copyright, trademark, or abuse concerns, use the <Link className="text-[#b8adff]" href="/report">private report form</Link>. For product and security questions, use the <Link className="text-[#b8adff]" href="/contact">contact page</Link>. Also read the <Link className="text-[#b8adff]" href="/terms">Terms</Link>.</p></section>
      </article>
    </SeoPageShell>
  );
}
