import type { Metadata } from "next";
import Link from "next/link";
import { SeoPageShell, sectionClass } from "@/components/SeoPageShell";
import { absoluteUrl } from "@/lib/site";

export const metadata: Metadata = { title: "Terms of Service", description: "Terms governing the free Get Codex Theme gallery, community publishing, author attribution, validation, likes, and open-source installation tools.", alternates: { canonical: absoluteUrl("/terms") } };

export default function TermsPage() {
  return (
    <SeoPageShell eyebrow="Legal · Updated July 23, 2026" title="Terms of Service" description={<p>These terms cover the free theme gallery, community Registry, publisher accounts, and open-source tools.</p>} breadcrumbs={[{ label: "Home", href: "/" }, { label: "Terms" }]} compact>
      <article className={`${sectionClass} max-w-4xl space-y-12 text-base leading-8 text-white/62`}>
        <section><h2 className="[font-family:var(--font-heading)] text-4xl text-white">1. The service</h2><p className="mt-5">Get Codex Theme provides an unofficial gallery, free Registry downloads, an automated publishing workflow, theme-pack specification, CLI, and compatibility tools for Codex Desktop. Browsing and installation require no account. Google or GitHub sign-in plus exactly one public GitHub or X contributor profile is required for each publishing session.</p></section>
        <section><h2 className="[font-family:var(--font-heading)] text-4xl text-white">2. Unofficial status and compatibility</h2><p className="mt-5">Get Codex Theme is not affiliated with, endorsed by, or sponsored by OpenAI. Codex and related marks belong to their respective owner. Advanced image-based themes use an unofficial local compatibility runtime and may be affected by Codex updates. The CLI never modifies the signed Codex application bundle.</p></section>
        <section><h2 className="[font-family:var(--font-heading)] text-4xl text-white">3. Your submissions</h2><p className="mt-5">You retain ownership of original assets you submit. You grant us a non-exclusive license to validate, sanitize, store, reproduce, display, package, and distribute a successfully validated theme through the Registry under the license stated in its manifest and rights record. You confirm that you have the rights needed to publish every asset, name, logo, and reference.</p></section>
        <section><h2 className="[font-family:var(--font-heading)] text-4xl text-white">4. Automated publication and removal</h2><p className="mt-5">A release is published only when automated identity, package, checksum, rights-record, and server validation succeeds. Failed validation must be corrected and resubmitted. We may later suspend or remove a theme for credible safety, rights, deceptive metadata, broken installation, or policy concerns. Published versions are immutable; updates require a new semantic version. A theme ID remains associated with its original authenticated publisher to prevent namespace takeover.</p></section>
        <section><h2 className="[font-family:var(--font-heading)] text-4xl text-white">5. Attribution and links</h2><p className="mt-5">Publishers select exactly one GitHub or X profile for public contributor credit. The selected username and profile link are displayed on gallery cards and theme pages. GitHub profiles may be linked through Neon Auth. X profile links are supplied by the publisher and are not verified through the X API. The publishing manifest must use the same saved attribution. By using a profile, you confirm that it represents you or an organization you are authorized to publish for. Do not impersonate another creator or organization.</p></section>
        <section><h2 className="[font-family:var(--font-heading)] text-4xl text-white">6. Acceptable use</h2><p className="mt-5">Do not upload malware, executable payloads, credentials, private data, illegal material, deceptive interface imagery, or assets you lack permission to distribute. Do not automate likes, evade rate limits, overload public endpoints, manipulate popularity, or interfere with another publisher&apos;s namespace. Uploaded executable files are removed from Registry packs.</p></section>
        <section><h2 className="[font-family:var(--font-heading)] text-4xl text-white">7. Reports and removal</h2><p className="mt-5">We may correct, disable, or remove a listing or release in response to a credible copyright, trademark, privacy, safety, or abuse report. Submit those concerns through the private report form. False or abusive reports may be rejected and rate-limited.</p></section>
        <section><h2 className="[font-family:var(--font-heading)] text-4xl text-white">8. Licenses and downloads</h2><p className="mt-5">Each theme is governed by the license included in its download. The CLI and public project components are governed by their repository licenses. Creator attribution shown by the site does not replace the theme&apos;s license terms.</p></section>
        <section><h2 className="[font-family:var(--font-heading)] text-4xl text-white">9. Disclaimers and changes</h2><p className="mt-5">The service and tools are provided on an “as available” basis without warranties to the maximum extent permitted by law. We may update the service or these terms, with material changes reflected by the updated date. See the <Link className="text-[#b8adff]" href="/privacy">Privacy Policy</Link>, use the <Link className="text-[#b8adff]" href="/report">private report form</Link> for rights or removal requests, or visit the <Link className="text-[#b8adff]" href="/contact">contact page</Link> for product support.</p></section>
      </article>
    </SeoPageShell>
  );
}
