import type { CodexTheme } from "./themes";

export type ConceptCategory = "Mascots" | "Brand concepts" | "Gaming" | "Culture" | "Aesthetic";

export type ConceptTheme = CodexTheme & {
  category: ConceptCategory;
  artDirection: string;
  workspaceFit: string;
  previewReady: boolean;
  previewImage?: string;
  inspiration?: string;
  trademarkNotice?: string;
};

type ConceptSeed = {
  slug: string;
  name: string;
  category: ConceptCategory;
  mode: "dark" | "light";
  tagline: string;
  description: string;
  accent: string;
  accentStrong: string;
  secondary: string;
  tags: string[];
  artDirection: string;
  workspaceFit: string;
  previewReady?: boolean;
  inspiration?: string;
};

const brandNotice = (name: string) =>
  `${name} is a trademark of its respective owner. This independent concept is not sponsored, approved, or affiliated with that company; its brand mark identifies the visual direction.`;

function buildConcept(seed: ConceptSeed, index: number): ConceptTheme {
  const dark = seed.mode === "dark";
  return {
    ...seed,
    foreground: dark ? "#f7f8fb" : "#202226",
    muted: dark ? "#aeb3c0" : "#666b73",
    surface: dark ? "rgba(12, 14, 20, 0.88)" : "rgba(255, 255, 255, 0.86)",
    canvas: dark ? "#080a0f" : "#f2f2ef",
    gradient: `radial-gradient(circle at 82% 34%, ${seed.accent}cc, transparent 22%), radial-gradient(circle at 70% 72%, ${seed.secondary}aa, transparent 32%), linear-gradient(140deg, ${dark ? "#05060a" : "#faf9f5"} 0%, ${seed.accentStrong} 145%)`,
    focusX: 79,
    focusY: 48,
    order: 1_000 + index * 10,
    previewReady: Boolean(seed.previewReady),
    previewImage: seed.previewReady ? `/concept-themes/${seed.slug}/background.jpg` : undefined,
    trademarkNotice: seed.inspiration ? brandNotice(seed.inspiration) : undefined,
  };
}

const seeds: ConceptSeed[] = [
  {
    slug: "pocket-robot-cat",
    name: "Pocket Robot Cat",
    category: "Mascots",
    mode: "dark",
    tagline: "A tiny blue co-pilot for ambitious builds.",
    description: "An original cobalt robot cat watches over a midnight workshop filled with modular gadgets and soft electric light.",
    accent: "#42b9ff",
    accentStrong: "#174b80",
    secondary: "#ffb94a",
    tags: ["Robot cat", "Blue", "Playful"],
    artDirection: "A completely original rounded robot cat with expressive LED eyes, small antenna ears, and modular tool panels; no bell, belly pocket, copied face, or copyrighted character silhouette.",
    workspaceFit: "The mascot stays on the far right while a calm navy field protects thread text, diffs, and the composer on the left.",
    previewReady: true,
  },
  {
    slug: "capybara-cafe",
    name: "Capybara Café",
    category: "Mascots",
    mode: "light",
    tagline: "Unbothered energy for long coding sessions.",
    description: "A relaxed capybara runs a warm wood-and-citrus café while your workspace stays bright, soft, and readable.",
    accent: "#c7773f",
    accentStrong: "#6d3f2b",
    secondary: "#f2c76d",
    tags: ["Capybara", "Cozy", "Café"],
    artDirection: "Editorial 3D illustration of a capybara barista beside a tiny espresso station, orange slices, linen, oak, and morning window light.",
    workspaceFit: "Warm surfaces create personality without putting detailed objects behind the task column or composer.",
    previewReady: true,
  },
  {
    slug: "corgi-astronaut",
    name: "Corgi Astronaut",
    category: "Mascots",
    mode: "dark",
    tagline: "Short legs. Interplanetary ambitions.",
    description: "A brave corgi floats beside a compact lunar workstation with optimistic orange-and-blue mission lighting.",
    accent: "#ff9b45",
    accentStrong: "#7a3b20",
    secondary: "#4e7dff",
    tags: ["Corgi", "Space", "Mission"],
    artDirection: "A cinematic but friendly corgi in an original compact spacesuit, floating near a moon-window workstation with no agency marks or copied mission hardware.",
    workspaceFit: "The bright character anchors the right edge; deep space gives the Codex interface a low-glare working field.",
    previewReady: true,
  },
  {
    slug: "red-panda-hacker",
    name: "Red Panda Hacker",
    category: "Mascots",
    mode: "dark",
    tagline: "Curious, quick, and terminal obsessed.",
    description: "An original red panda tinkers with a pocket-sized terminal inside a rain-lit rooftop studio.",
    accent: "#ff6b35",
    accentStrong: "#6f271d",
    secondary: "#35d6c9",
    tags: ["Red panda", "Terminal", "Rain"],
    artDirection: "Stylized red panda engineer surrounded by cables, compact keyboards, rain glass, teal reflections, and handmade electronics.",
    workspaceFit: "Orange fur and teal rim light remain outside the reading lane while the center stays nearly black for code contrast.",
    previewReady: true,
  },
  {
    slug: "axolotl-aquarium",
    name: "Axolotl Aquarium",
    category: "Mascots",
    mode: "dark",
    tagline: "A quiet underwater companion for deep work.",
    description: "A smiling axolotl drifts through an otherworldly planted aquarium with lavender bioluminescence.",
    accent: "#e482ff",
    accentStrong: "#54326c",
    secondary: "#45d9d0",
    tags: ["Axolotl", "Aquarium", "Bioluminescent"],
    artDirection: "Dreamlike underwater macro scene with an original axolotl, translucent plants, soft bubbles, purple coral light, and deep cyan water.",
    workspaceFit: "Soft aquatic depth adds motion and charm while dark water preserves a clean interface silhouette.",
    previewReady: true,
  },
  {
    slug: "spacex-launchpad",
    name: "SpaceX Launchpad Concept",
    category: "Brand concepts",
    mode: "dark",
    tagline: "A launch-night workspace for shipping ambitious systems.",
    description: "An unofficial SpaceX-inspired Codex theme concept built around launch telemetry, vapor, and a disciplined black-and-white control room.",
    accent: "#e8edf6",
    accentStrong: "#27344c",
    secondary: "#e7633d",
    tags: ["SpaceX", "Launch", "Telemetry"],
    artDirection: "An original near-future launch facility at night with a generic reusable rocket silhouette, vapor, floodlights, and abstract telemetry panels; no logos or copied vehicle design.",
    workspaceFit: "The high-energy launch moment stays at the horizon while the primary task surface remains controlled and nearly monochrome.",
    previewReady: true,
    inspiration: "SpaceX",
  },
  {
    slug: "google-spectrum",
    name: "Google Spectrum Concept",
    category: "Brand concepts",
    mode: "light",
    tagline: "Search-inspired color with Material clarity.",
    description: "An unofficial Google-inspired Codex concept using playful primary-color geometry and a clean white working canvas.",
    accent: "#4285f4",
    accentStrong: "#2855a6",
    secondary: "#fbbc04",
    tags: ["Google", "Spectrum", "Material"],
    artDirection: "Original spatial composition of soft geometric tiles in blue, red, yellow, and green, with paper-like depth and no letterforms or official marks.",
    workspaceFit: "Color lives in modular edge elements while the thread and composer retain a calm neutral surface.",
    previewReady: true,
    inspiration: "Google",
  },
  {
    slug: "meta-horizon",
    name: "Meta Horizon Concept",
    category: "Brand concepts",
    mode: "dark",
    tagline: "A social-computing horizon without the noise.",
    description: "An unofficial Meta-inspired Codex concept shaped by luminous spatial arcs, deep blue distance, and a calm mixed-reality studio.",
    accent: "#4f8cff",
    accentStrong: "#233f87",
    secondary: "#ab7cff",
    tags: ["Meta", "Horizon", "Spatial"],
    artDirection: "Original abstract mixed-reality landscape with layered blue and violet portals, distant social nodes, and no infinity mark or product UI.",
    workspaceFit: "Large arcs guide attention toward the work area without placing bright nodes beneath copy or code.",
    previewReady: true,
    inspiration: "Meta",
  },
  {
    slug: "openai-monochrome-lab",
    name: "OpenAI Monochrome Lab Concept",
    category: "Brand concepts",
    mode: "light",
    tagline: "Research-lab restraint for focused iteration.",
    description: "An unofficial OpenAI-inspired Codex concept with monochrome research materials, soft paper light, and precise scientific calm.",
    accent: "#1f7568",
    accentStrong: "#16483f",
    secondary: "#9ab8b1",
    tags: ["OpenAI", "Monochrome", "Research"],
    artDirection: "Original AI research studio with translucent model layers, graph paper, matte ceramic instruments, and abstract cellular geometry; no knot mark or company typography.",
    workspaceFit: "A neutral visual hierarchy keeps prompts and diffs primary while subtle green structure signals the research theme.",
    previewReady: true,
    inspiration: "OpenAI",
  },
  {
    slug: "nvidia-neon-compute",
    name: "NVIDIA Neon Compute Concept",
    category: "Brand concepts",
    mode: "dark",
    tagline: "Parallel energy for heavy builds.",
    description: "An unofficial NVIDIA-inspired Codex concept with electric green compute fields and disciplined data-center depth.",
    accent: "#85d92f",
    accentStrong: "#315c18",
    secondary: "#31d8a4",
    tags: ["NVIDIA", "GPU", "Compute"],
    artDirection: "Original abstract compute chamber with green light matrices, dark modular hardware, airflow traces, and no eye logo, board design, or product marks.",
    workspaceFit: "The neon matrix adds speed at the far edge while black glass surfaces keep terminal content readable.",
    previewReady: true,
    inspiration: "NVIDIA",
  },
  {
    slug: "shiba-ramen",
    name: "Shiba Ramen Shop",
    category: "Mascots",
    mode: "dark",
    tagline: "Late-night comfort for one more commit.",
    description: "A cheerful shiba chef works behind a tiny lantern-lit ramen counter after midnight.",
    accent: "#f08a3c",
    accentStrong: "#6f321d",
    secondary: "#d94747",
    tags: ["Shiba", "Ramen", "Night"],
    artDirection: "Warm miniature ramen shop with an original shiba chef, steam, wood, red paper lanterns, and a rainy alley beyond.",
    workspaceFit: "The shop creates a comforting right-side vignette while the dark street leaves room for high-contrast task content.",
    previewReady: true,
  },
  {
    slug: "penguin-terminal",
    name: "Penguin Terminal",
    category: "Mascots",
    mode: "dark",
    tagline: "Cold environment, warm little operator.",
    description: "A determined penguin manages a polar research terminal under a green aurora.",
    accent: "#65e3c2",
    accentStrong: "#22594e",
    secondary: "#73a8ff",
    tags: ["Penguin", "Terminal", "Polar"],
    artDirection: "Original penguin scientist beside rugged generic computers in an Antarctic shelter, with aurora glow and frost-textured windows.",
    workspaceFit: "Cool darkness and broad sky keep the interface calm while the small mascot supplies a memorable focal point.",
    previewReady: true,
  },
  {
    slug: "otter-workshop",
    name: "Otter Workshop",
    category: "Mascots",
    mode: "light",
    tagline: "Craft, test, float, repeat.",
    description: "A clever river otter assembles tiny mechanical tools in a sunlit waterside workshop.",
    accent: "#3f8f89",
    accentStrong: "#285854",
    secondary: "#df9b4e",
    tags: ["Otter", "Workshop", "Craft"],
    artDirection: "Tactile storybook workshop with an original otter maker, brass tools, river stones, linen, and reflected daylight.",
    workspaceFit: "Natural materials make a friendly light theme while low-detail plaster provides a clean task background.",
    previewReady: true,
  },
  {
    slug: "black-cat-midnight",
    name: "Black Cat Midnight",
    category: "Mascots",
    mode: "dark",
    tagline: "Silent supervision for serious debugging.",
    description: "A black cat sits beside a moonlit monitor in a nearly silent apartment studio.",
    accent: "#9d89ff",
    accentStrong: "#423773",
    secondary: "#4f74a8",
    tags: ["Black cat", "Midnight", "Minimal"],
    artDirection: "Minimal cinematic room, original black cat silhouette, moonlight, one desk lamp, soft curtains, and subtle violet reflections.",
    workspaceFit: "Low visual noise and deep neutral surfaces make this a practical daily dark theme, not only a novelty image.",
    previewReady: true,
  },
  {
    slug: "frog-rainy-desk",
    name: "Frog Rainy Desk",
    category: "Mascots",
    mode: "dark",
    tagline: "Tiny desk, enormous concentration.",
    description: "A small green frog works from a leaf-roof desk while rain beads across the window.",
    accent: "#80c96b",
    accentStrong: "#355e32",
    secondary: "#5aa7b5",
    tags: ["Frog", "Rain", "Cozy"],
    artDirection: "Original miniature frog workspace with moss, a leaf canopy, warm lamp, rainy glass, and handcrafted keyboard details.",
    workspaceFit: "Rain and moss soften the scene while the central glass remains dark and uncluttered for the interface.",
    previewReady: true,
  },
  {
    slug: "apple-liquid-studio",
    name: "Apple Liquid Studio Concept",
    category: "Brand concepts",
    mode: "light",
    tagline: "Polished translucency for a meticulous workspace.",
    description: "An unofficial Apple-inspired concept pairing milky glass, precise aluminum, and diffused daylight.",
    accent: "#6288c7",
    accentStrong: "#435d86",
    secondary: "#d9c6ff",
    tags: ["Apple", "Liquid glass", "Studio"],
    artDirection: "Original minimal product studio with layered translucent panels, brushed metal, soft spectral highlights, and no fruit mark or device replica.",
    workspaceFit: "Controlled translucency adds polish while solid white surfaces preserve legibility and predictable contrast.",
    previewReady: true,
    inspiration: "Apple",
  },
  {
    slug: "microsoft-fluent-grid",
    name: "Microsoft Fluent Grid Concept",
    category: "Brand concepts",
    mode: "light",
    tagline: "Modular clarity for multi-project work.",
    description: "An unofficial Microsoft-inspired theme concept built from depth, modular panes, and restrained blue light.",
    accent: "#397bd5",
    accentStrong: "#27518c",
    secondary: "#69b7a5",
    tags: ["Microsoft", "Fluent", "Grid"],
    artDirection: "Original architectural grid of frosted panes and colored light blocks, with no four-square mark, Windows UI, or product icons.",
    workspaceFit: "The modular rhythm complements Codex navigation and thread groupings without competing with actual controls.",
    previewReady: true,
    inspiration: "Microsoft",
  },
  {
    slug: "tesla-cyber-garage",
    name: "Tesla Cyber Garage Concept",
    category: "Brand concepts",
    mode: "dark",
    tagline: "Industrial precision with electric tension.",
    description: "An unofficial Tesla-inspired concept with angular architecture, charging light, and a stark concrete garage.",
    accent: "#e43d46",
    accentStrong: "#672329",
    secondary: "#76879a",
    tags: ["Tesla", "Cyber", "Industrial"],
    artDirection: "Original brutalist EV design studio with abstract angular sculpture, charging rails, dark concrete, and no vehicle or T emblem.",
    workspaceFit: "Hard geometry frames the edge of the screen while the main workspace uses low-glare charcoal surfaces.",
    previewReady: true,
    inspiration: "Tesla",
  },
  {
    slug: "anthropic-warm-lab",
    name: "Anthropic Warm Lab Concept",
    category: "Brand concepts",
    mode: "light",
    tagline: "Human-scale research with editorial warmth.",
    description: "An unofficial Anthropic-inspired concept using clay, paper, warm cream, and quiet research-room detail.",
    accent: "#c46d46",
    accentStrong: "#784832",
    secondary: "#d8b792",
    tags: ["Anthropic", "Research", "Warm"],
    artDirection: "Original editorial AI lab with paper models, terracotta objects, annotated blank cards, natural wood, and no company marks or copied site design.",
    workspaceFit: "Warm neutrals reduce sterile software energy while dark text maintains long-form reading comfort.",
    previewReady: true,
    inspiration: "Anthropic",
  },
  {
    slug: "amazon-orbit-logistics",
    name: "Amazon Orbit Logistics Concept",
    category: "Brand concepts",
    mode: "dark",
    tagline: "Systems thinking at planetary scale.",
    description: "An unofficial Amazon-inspired concept turning logistics paths and orbital routing into a focused command center.",
    accent: "#ffb23f",
    accentStrong: "#70461c",
    secondary: "#4fa7d8",
    tags: ["Amazon", "Logistics", "Orbit"],
    artDirection: "Original abstract logistics map across a dark planet, with amber routes, blue depots, generic cargo forms, and no smile arrow or branded boxes.",
    workspaceFit: "Route lines create peripheral movement while the center remains dark enough for dense task histories.",
    previewReady: true,
    inspiration: "Amazon",
  },
  {
    slug: "x-signal-network",
    name: "X Signal Network Concept",
    category: "Brand concepts",
    mode: "dark",
    tagline: "A real-time builder workspace connected to the conversation.",
    description: "An X-inspired Codex concept combining monochrome signal architecture, live developer conversation, Spaces, and a focused post composer.",
    accent: "#ffffff",
    accentStrong: "#202327",
    secondary: "#71767b",
    tags: ["X", "Twitter", "Social"],
    artDirection: "A stark monochrome communications landscape with white signal paths, a distant broadcast structure, and the official X mark integrated into the coded interface rather than painted into the background.",
    workspaceFit: "The live-feed language occupies structured interface zones while a near-black reading field keeps Codex threads, diffs, and the composer highly legible.",
    previewReady: true,
    inspiration: "X",
  },
  {
    slug: "pixel-dungeon",
    name: "Pixel Dungeon",
    category: "Gaming",
    mode: "dark",
    tagline: "Every task is another room to clear.",
    description: "A richly lit original pixel-art dungeon turns project progress into a cozy exploration map.",
    accent: "#d89b4b",
    accentStrong: "#704521",
    secondary: "#795bd6",
    tags: ["Pixel art", "Dungeon", "Retro"],
    artDirection: "Original high-detail pixel environment with torchlight, stone corridors, treasure-map geometry, and no recognizable game characters or UI.",
    workspaceFit: "The level sits at the right edge and uses controlled pixel density so text remains the primary signal.",
    previewReady: true,
  },
  {
    slug: "mecha-hangar",
    name: "Mecha Hangar",
    category: "Gaming",
    mode: "dark",
    tagline: "Large machines, exact checklists.",
    description: "An original maintenance hangar frames a towering unbranded robot with engineering lights and floor markings.",
    accent: "#ff7048",
    accentStrong: "#6c3025",
    secondary: "#44a9c8",
    tags: ["Mecha", "Hangar", "Engineering"],
    artDirection: "Original industrial robot silhouette, service gantries, small technicians, safety lights, and no anime franchise shapes or insignia.",
    workspaceFit: "Vertical machinery gives the theme identity while the darker bay becomes a practical reading field.",
    previewReady: true,
  },
  {
    slug: "cyberpunk-rain",
    name: "Cyberpunk Rain",
    category: "Gaming",
    mode: "dark",
    tagline: "Neon atmosphere without neon overload.",
    description: "A rain-soaked original megacity uses cyan and magenta reflections around a protected dark workspace.",
    accent: "#37d9ff",
    accentStrong: "#1c5574",
    secondary: "#ff4eb8",
    tags: ["Cyberpunk", "Rain", "City"],
    artDirection: "Original futuristic alley with abstract signs containing no readable text, wet pavement, layered transit, and atmospheric haze.",
    workspaceFit: "Bright reflections are edge-weighted and softened so the interface still behaves like a serious dark theme.",
    previewReady: true,
  },
  {
    slug: "retro-arcade",
    name: "Retro Arcade",
    category: "Gaming",
    mode: "dark",
    tagline: "Insert focus. Press start.",
    description: "An original 1980s arcade room glows with geometric cabinets, scanlines, and electric carpet patterns.",
    accent: "#ff4fd8",
    accentStrong: "#69255f",
    secondary: "#46e1ff",
    tags: ["Arcade", "80s", "Neon"],
    artDirection: "Generic arcade cabinets with abstract screens, geometric carpet, magenta tubes, cyan haze, and no game marquees or recognizable characters.",
    workspaceFit: "The nostalgia lives in the background while the thread column keeps a modern neutral contrast system.",
    previewReady: true,
  },
  {
    slug: "cozy-farm",
    name: "Cozy Farm",
    category: "Gaming",
    mode: "light",
    tagline: "Small progress, beautifully tended.",
    description: "A miniature original farm scene turns tasks into a calm morning routine of paths, plots, and tiny barns.",
    accent: "#68a85f",
    accentStrong: "#476f42",
    secondary: "#e5a858",
    tags: ["Cozy game", "Farm", "Morning"],
    artDirection: "Original isometric farm with simple crops, a small river, warm roofs, and no copied game sprites, characters, or interface.",
    workspaceFit: "Soft top-down geometry feels playful but leaves broad pale areas for long-form Codex responses.",
    previewReady: true,
  },
  {
    slug: "tactical-map",
    name: "Tactical Map",
    category: "Gaming",
    mode: "dark",
    tagline: "Plan the change before you move.",
    description: "A fictional command map layers terrain, routes, and objective markers into a disciplined olive workspace.",
    accent: "#b7c36a",
    accentStrong: "#525a2d",
    secondary: "#d27a47",
    tags: ["Tactical", "Map", "Strategy"],
    artDirection: "Original topographic map table with generic terrain, abstract markers, red string routes, and no real military insignia or classified imagery.",
    workspaceFit: "Map structure supports planning metaphors while muted olive surfaces avoid visual fatigue.",
    previewReady: true,
  },
  {
    slug: "neon-racer",
    name: "Neon Racer",
    category: "Gaming",
    mode: "dark",
    tagline: "Fast iteration on an endless night road.",
    description: "A fictional electric raceway cuts through a violet desert with long cyan light trails.",
    accent: "#53d7ff",
    accentStrong: "#214f76",
    secondary: "#9a59ff",
    tags: ["Racing", "Synthwave", "Speed"],
    artDirection: "Original futuristic road, abstract low-slung vehicle light trail, distant mountains, and no manufacturer badges or recognizable car design.",
    workspaceFit: "Strong perspective adds momentum but vanishes behind the main panel through a deliberate dark overlay.",
    previewReady: true,
  },
  {
    slug: "fantasy-guild",
    name: "Fantasy Guild",
    category: "Gaming",
    mode: "dark",
    tagline: "Turn the backlog into a quest board.",
    description: "An original adventurers' guild combines candlelight, maps, carved wood, and a wall of blank quest cards.",
    accent: "#d8a55c",
    accentStrong: "#69482a",
    secondary: "#6b8f73",
    tags: ["Fantasy", "Guild", "Quest"],
    artDirection: "Original medieval guild interior with blank parchment cards, maps, warm lanterns, plants, and no franchise crests or characters.",
    workspaceFit: "The tactile setting makes task management feel thematic while solid dark panels preserve modern usability.",
    previewReady: true,
  },
  {
    slug: "lunar-base",
    name: "Lunar Base",
    category: "Gaming",
    mode: "dark",
    tagline: "A quiet outpost for difficult problems.",
    description: "An original moon base interior looks across a crater field toward Earthrise and sparse utility lights.",
    accent: "#8cb7ff",
    accentStrong: "#324d75",
    secondary: "#e4b36a",
    tags: ["Moon", "Base", "Sci-fi"],
    artDirection: "Original functional lunar habitat with a large window, generic consoles, equipment bags, dust, and no agency or film-franchise references.",
    workspaceFit: "The lunar horizon is cinematic but visually quiet, ideal for a low-distraction Codex window.",
    previewReady: true,
  },
  {
    slug: "deep-sea-station",
    name: "Deep Sea Station",
    category: "Gaming",
    mode: "dark",
    tagline: "Pressure-tested focus below the surface.",
    description: "A fictional undersea research station glows beside immense blue water and drifting bioluminescent life.",
    accent: "#3ccbd4",
    accentStrong: "#205763",
    secondary: "#6f79d8",
    tags: ["Ocean", "Station", "Bioluminescent"],
    artDirection: "Original underwater habitat, thick windows, distant jellyfish-like lights, steel ribs, and no recognizable game or film environment.",
    workspaceFit: "Deep blue water creates natural negative space while small lights keep the scene alive.",
    previewReady: true,
  },
  {
    slug: "dragon-library",
    name: "Dragon Library",
    category: "Gaming",
    mode: "dark",
    tagline: "Ancient knowledge, modern execution.",
    description: "An original small dragon curls around the upper shelves of a monumental candlelit library.",
    accent: "#d69b55",
    accentStrong: "#6f4327",
    secondary: "#7e4e9f",
    tags: ["Dragon", "Library", "Fantasy"],
    artDirection: "Original scholarly dragon design, towering book stacks, ladders, candles, dust rays, and no franchise heraldry or creature likeness.",
    workspaceFit: "Warm shelf geometry surrounds rather than obstructs the central interface, creating depth without noise.",
    previewReady: true,
  },
  {
    slug: "manga-ink",
    name: "Manga Ink",
    category: "Culture",
    mode: "light",
    tagline: "Decisive black lines on a paper-white canvas.",
    description: "An original manga-inspired workspace uses speed lines, halftone texture, and blank panel rhythm without copying any series.",
    accent: "#e45252",
    accentStrong: "#7b3030",
    secondary: "#727272",
    tags: ["Manga", "Ink", "Halftone"],
    artDirection: "Original monochrome comic panels with abstract city fragments, expressive brush marks, sparse red accents, and no recognizable characters.",
    workspaceFit: "High-contrast paper and deliberate panel gaps mirror Codex structure while keeping text exceptionally readable.",
    previewReady: true,
  },
  {
    slug: "kaiju-night",
    name: "Kaiju Night",
    category: "Culture",
    mode: "dark",
    tagline: "Big incident. Calm operator.",
    description: "An original colossal creature silhouette moves beyond a rain-lit harbor while the command room remains composed.",
    accent: "#ff6846",
    accentStrong: "#713026",
    secondary: "#487bb7",
    tags: ["Kaiju", "Harbor", "Cinematic"],
    artDirection: "Original giant creature silhouette with non-franchise anatomy, distant harbor cranes, rain, searchlights, and no city branding.",
    workspaceFit: "Scale creates drama at the horizon, but the nearby control room supplies a stable dark reading surface.",
    previewReady: true,
  },
  {
    slug: "magical-library",
    name: "Magical Library",
    category: "Culture",
    mode: "dark",
    tagline: "A little wonder behind every command.",
    description: "Floating books and soft spell-light animate an original circular library filled with midnight blue shelves.",
    accent: "#b58cff",
    accentStrong: "#523b78",
    secondary: "#64d0c4",
    tags: ["Magic", "Library", "Books"],
    artDirection: "Original fantasy library with levitating blank books, glowing geometric sigils, spiral stairs, and no school crests or franchise props.",
    workspaceFit: "The glow is sparse and perimeter-weighted, making the atmosphere delightful without sacrificing code contrast.",
    previewReady: true,
  },
  {
    slug: "sakura-train",
    name: "Sakura Train",
    category: "Culture",
    mode: "light",
    tagline: "A gentle commute through focused work.",
    description: "A quiet original train carriage passes spring blossoms, pale mountains, and small coastal towns.",
    accent: "#d87591",
    accentStrong: "#8a4c61",
    secondary: "#7aa8c4",
    tags: ["Sakura", "Train", "Spring"],
    artDirection: "Original Japanese countryside train interior with no rail operator marks, softly framed blossoms, warm seats, and painted sky.",
    workspaceFit: "Wide windows create a calm moving backdrop while interior panels provide stable light-theme surfaces.",
    previewReady: true,
  },
  {
    slug: "bento-studio",
    name: "Bento Studio",
    category: "Culture",
    mode: "light",
    tagline: "Small compartments, beautifully organized.",
    description: "A playful overhead bento composition turns modular work into color, texture, and careful arrangement.",
    accent: "#d95c4f",
    accentStrong: "#863b35",
    secondary: "#6c9b65",
    tags: ["Bento", "Food", "Organized"],
    artDirection: "Original editorial food styling with rice, vegetables, lacquer dividers, linen, and no mascots, logos, or packaged products.",
    workspaceFit: "The modular composition echoes panels and task groups while a pale tabletop keeps the interface readable.",
    previewReady: true,
  },
  {
    slug: "yokai-lantern",
    name: "Yokai Lantern",
    category: "Culture",
    mode: "dark",
    tagline: "Folklore atmosphere for late-night builds.",
    description: "Original friendly spirits gather near stone lanterns on a misty forest path.",
    accent: "#f0a851",
    accentStrong: "#75451f",
    secondary: "#6ea38e",
    tags: ["Yokai", "Lantern", "Forest"],
    artDirection: "Original folklore-inspired spirits with simple non-franchise shapes, mossy stones, paper lanterns without text, mist, and cedar trees.",
    workspaceFit: "Lanterns form a low-frequency glow while forest shadow supports a comfortable dark UI.",
    previewReady: true,
  },
  {
    slug: "neon-shibuya",
    name: "Neon Shibuya",
    category: "Culture",
    mode: "dark",
    tagline: "Crossing energy with a protected focus lane.",
    description: "An original Tokyo-night intersection uses abstract signage, rain reflections, and elevated motion.",
    accent: "#ff4f9a",
    accentStrong: "#722b50",
    secondary: "#37ccff",
    tags: ["Tokyo", "Neon", "Street"],
    artDirection: "Original urban crossing inspired by Shibuya's energy, with unreadable abstract signs, generic buildings, umbrellas, and no store marks.",
    workspaceFit: "Activity concentrates at the far right and lower edge while the thread region remains deliberately subdued.",
    previewReady: true,
  },
  {
    slug: "wuxia-mountain",
    name: "Wuxia Mountain",
    category: "Culture",
    mode: "light",
    tagline: "Lightness, distance, and disciplined movement.",
    description: "An original ink-wash mountain world uses suspended paths, mist, and a distant solitary traveler.",
    accent: "#557a70",
    accentStrong: "#3b544e",
    secondary: "#b98a55",
    tags: ["Wuxia", "Ink wash", "Mountain"],
    artDirection: "Original Chinese ink-wash landscape with layered peaks, a tiny generic traveler, negative space, and no calligraphy or franchise costumes.",
    workspaceFit: "Traditional negative space translates naturally into an elegant and highly readable light theme.",
    previewReady: true,
  },
  {
    slug: "paper-lantern-market",
    name: "Paper Lantern Market",
    category: "Culture",
    mode: "dark",
    tagline: "A lively night market beyond a calm desk.",
    description: "A fictional lantern market layers textiles, food steam, and warm stalls along a narrow evening lane.",
    accent: "#f28645",
    accentStrong: "#793b23",
    secondary: "#d34b58",
    tags: ["Night market", "Lantern", "Warm"],
    artDirection: "Original pan-Asian night market scene with blank lanterns, generic stalls, patterned textiles, steam, and no visible brands or writing.",
    workspaceFit: "Warm light supplies personality while a cool foreground desk creates the necessary contrast boundary.",
    previewReady: true,
  },
  {
    slug: "desert-caravan",
    name: "Desert Caravan",
    category: "Culture",
    mode: "dark",
    tagline: "Long-distance focus under a vast sky.",
    description: "An original caravan crosses sculpted dunes beneath an indigo sky and a rising moon.",
    accent: "#d79555",
    accentStrong: "#744526",
    secondary: "#5255a0",
    tags: ["Desert", "Caravan", "Moon"],
    artDirection: "Original cinematic dune landscape, small generic caravan silhouettes, indigo twilight, textured sand, and no modern brands or landmarks.",
    workspaceFit: "Vast low-detail sky gives the interface breathing room while warm dunes create an unmistakable identity.",
    previewReady: true,
  },
  {
    slug: "dark-academia",
    name: "Dark Academia",
    category: "Aesthetic",
    mode: "dark",
    tagline: "Scholarly weight for careful reasoning.",
    description: "Walnut shelves, green glass lamps, annotated blank paper, and rainy stone build a focused old-library mood.",
    accent: "#b69a61",
    accentStrong: "#5d4d31",
    secondary: "#446151",
    tags: ["Dark academia", "Library", "Classic"],
    artDirection: "Original scholarly desk with leather, wood, brass, blank notes, old windows, and no institutional crests or readable book titles.",
    workspaceFit: "Deep brown and green surfaces are calm enough for daily work while tactile detail gives the theme emotional weight.",
    previewReady: true,
  },
  {
    slug: "bauhaus-workbench",
    name: "Bauhaus Workbench",
    category: "Aesthetic",
    mode: "light",
    tagline: "Function first, color with purpose.",
    description: "Primary forms, metal tools, and gridded paper create an original modernist design workbench.",
    accent: "#d74b3f",
    accentStrong: "#84312b",
    secondary: "#245b9f",
    tags: ["Bauhaus", "Geometry", "Design"],
    artDirection: "Original modernist still life of circles, bars, rulers, paper, and primary-color objects, without reproducing a specific artwork.",
    workspaceFit: "Strong geometry maps naturally to navigation and panels while the paper field keeps dense content legible.",
    previewReady: true,
  },
  {
    slug: "swiss-grid",
    name: "Swiss Grid",
    category: "Aesthetic",
    mode: "light",
    tagline: "Radical clarity for complex work.",
    description: "An editorial grid, red alignment marks, and generous white space create a disciplined visual system.",
    accent: "#e13d35",
    accentStrong: "#8c2925",
    secondary: "#7d8793",
    tags: ["Swiss", "Editorial", "Grid"],
    artDirection: "Original abstract international-typographic composition using blank blocks, alignment rules, neutral paper, and no copied poster or text.",
    workspaceFit: "The theme reinforces hierarchy and scanning, making it ideal for users who want almost no decorative distraction.",
    previewReady: true,
  },
  {
    slug: "brutalist-terminal",
    name: "Brutalist Terminal",
    category: "Aesthetic",
    mode: "dark",
    tagline: "Raw structure. Zero decoration.",
    description: "Concrete planes, exposed cable channels, and a single safety-orange signal define a hard technical workspace.",
    accent: "#ff6438",
    accentStrong: "#6f3023",
    secondary: "#777d82",
    tags: ["Brutalist", "Concrete", "Terminal"],
    artDirection: "Original brutalist interior with rough concrete, exposed services, modular lights, and no architecture copied from a specific building.",
    workspaceFit: "Flat charcoal planes give excellent contrast while the orange signal color reserves attention for active controls.",
    previewReady: true,
  },
  {
    slug: "synthwave-sunset",
    name: "Synthwave Sunset",
    category: "Aesthetic",
    mode: "dark",
    tagline: "Retro optimism after the sun goes down.",
    description: "A magenta sun, violet mountains, and a restrained perspective grid create a polished retro-future backdrop.",
    accent: "#ff5bbd",
    accentStrong: "#712d60",
    secondary: "#46c8ff",
    tags: ["Synthwave", "Sunset", "Retro"],
    artDirection: "Original retro-future landscape with geometric sun, low-poly mountains, subtle grid, and no copied album or game artwork.",
    workspaceFit: "The horizon sits above the composer and the grid fades under content, keeping the effect usable rather than gimmicky.",
    previewReady: true,
  },
  {
    slug: "cottagecore-window",
    name: "Cottagecore Window",
    category: "Aesthetic",
    mode: "light",
    tagline: "A gentle room for patient work.",
    description: "Wildflowers, linen curtains, old wood, and a misty garden make a restorative bright workspace.",
    accent: "#718f62",
    accentStrong: "#4b6541",
    secondary: "#d2a775",
    tags: ["Cottagecore", "Garden", "Cozy"],
    artDirection: "Original cottage desk scene with wildflowers, ceramic cup, blank notebook, linen, and an overgrown garden beyond the window.",
    workspaceFit: "Soft daylight and natural neutrals reduce fatigue while the desktop remains visually simple.",
    previewReady: true,
  },
  {
    slug: "vaporwave-pool",
    name: "Vaporwave Pool",
    category: "Aesthetic",
    mode: "dark",
    tagline: "Surreal calm in electric pastel.",
    description: "An empty tiled pool reflects lavender architecture, a cyan night sky, and a distant coral moon.",
    accent: "#a86dff",
    accentStrong: "#503378",
    secondary: "#45d8dc",
    tags: ["Vaporwave", "Pool", "Surreal"],
    artDirection: "Original surreal pool architecture with pastel tiles, geometric arches, reflections, and no statues, logos, or album-art replication.",
    workspaceFit: "Large smooth surfaces carry the palette while dark water and shadow preserve text contrast.",
    previewReady: true,
  },
  {
    slug: "lofi-bedroom",
    name: "Lo-fi Bedroom",
    category: "Aesthetic",
    mode: "dark",
    tagline: "Quiet beats for focused builds.",
    description: "A rain-window bedroom studio uses warm lamp light, plants, records, and an empty late-night desk.",
    accent: "#d77f66",
    accentStrong: "#70443a",
    secondary: "#536b9a",
    tags: ["Lo-fi", "Bedroom", "Rain"],
    artDirection: "Original cozy room illustration with no person, no recognizable poster or album cover, warm lamp, plants, headphones, and rain outside.",
    workspaceFit: "The intimate scene feels familiar while the empty desk and dark window form low-detail UI zones.",
    previewReady: true,
  },
  {
    slug: "terminal-green",
    name: "Terminal Green",
    category: "Aesthetic",
    mode: "dark",
    tagline: "Phosphor discipline for command-line minds.",
    description: "A modern take on monochrome terminal glow uses deep black, soft phosphor green, and subtle scan texture.",
    accent: "#65e887",
    accentStrong: "#245b36",
    secondary: "#8eb99b",
    tags: ["Terminal", "Green", "Minimal"],
    artDirection: "Original abstract terminal-room atmosphere with blank phosphor screens, scanline haze, dark hardware, and no readable command output.",
    workspaceFit: "A near-monochrome palette keeps attention on state changes and makes active controls immediately obvious.",
    previewReady: true,
  },
  {
    slug: "paper-cut-garden",
    name: "Paper Cut Garden",
    category: "Aesthetic",
    mode: "light",
    tagline: "Layered craft with generous breathing room.",
    description: "Hand-cut botanical layers create depth through cream paper, sage leaves, and coral flowers.",
    accent: "#dc735e",
    accentStrong: "#895044",
    secondary: "#7b9b72",
    tags: ["Paper cut", "Garden", "Craft"],
    artDirection: "Original layered paper illustration with botanical silhouettes, visible fibers, soft shadows, and no text or copied pattern.",
    workspaceFit: "The material depth feels rich while broad cream areas support a clean light interface.",
    previewReady: true,
  },
  {
    slug: "midcentury-studio",
    name: "Mid-century Studio",
    category: "Aesthetic",
    mode: "light",
    tagline: "Warm modernism for deliberate work.",
    description: "Walnut furniture, terracotta, mustard, and sculptural light shape a composed design studio.",
    accent: "#c76d3f",
    accentStrong: "#78482f",
    secondary: "#6b8b83",
    tags: ["Mid-century", "Studio", "Warm"],
    artDirection: "Original mid-century-inspired room with generic furniture forms, ceramic objects, textured plaster, and no replicated designer product.",
    workspaceFit: "Warm neutral planes create personality without sacrificing the contrast expected from a professional tool.",
    previewReady: true,
  },
];

export const conceptThemes = seeds.map(buildConcept);

export function getConceptTheme(slug: string) {
  return conceptThemes.find((theme) => theme.slug === slug);
}

export function getRelatedConceptThemes(theme: ConceptTheme, limit = 4) {
  const sameCategory = conceptThemes.filter((candidate) => candidate.slug !== theme.slug && candidate.category === theme.category);
  const others = conceptThemes.filter((candidate) => candidate.slug !== theme.slug && candidate.category !== theme.category);
  return [...sameCategory, ...others].slice(0, limit);
}

export const conceptCategories: ConceptCategory[] = ["Mascots", "Brand concepts", "Gaming", "Culture", "Aesthetic"];
