/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.jsonc --include-runtime=false` (hash: 362a481b3508d2de5bf9788e138458f4)
interface __BaseEnv_Env {
	THEME_ASSETS: R2Bucket;
	DB: D1Database;
	ASSETS: Fetcher;
	SITE_URL: "https://getcodextheme.com";
	ENVIRONMENT: "production";
	NEON_AUTH_BASE_URL: string;
	NEON_AUTH_COOKIE_SECRET: string;
	LIKE_HASH_SECRET: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./dist/server/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "SITE_URL" | "ENVIRONMENT" | "NEON_AUTH_BASE_URL" | "NEON_AUTH_COOKIE_SECRET" | "LIKE_HASH_SECRET">> {}
}
